create;
create table;
create table f();
create table ff(123 int, 456 int);
create table fa(,a int);
create table fb(,,a int);
create table fc(a int,);
create table fd(int int);
create table fe(varchar varchar(40));
create table ff(int a, int b);
create table fg(c int primary, d int primary);
create table fh(a int primary key, b int, c intt);
create table fi(a int primary key, b int, c varchar(0));
create table fj(a varchar(-1));
create table fff(a varchar(41));
create table f(a int primary key, b int, c varchar(30));
create table g(a int, b int, c varchar(30));
insert f(a, b) values(1, 2);
insert into f values(100);
insert into f values(1, 2, 3);
insert into f values(1, 2, 'insert into f values(1, 2, 3) is wrong');
insert into f values(1, 2, 'create a very large table is very difficult');
insert into f values(1, 2, '3');
insert into f(a) values(2);
insert into f(b) values(2);
insert into f((c)) values('5');
insert into f(a, b, c) values();
insert into f(a, b, c) values(1);
insert into f(a, b, c) values(2, 2, 3);
insert into f(a, b, c) values(2, 2, '3');
insert into f(a, b, c) values('3', '2', '3');
insert into f(a, b, c) values(1, 2, 3, 4);
insert into f(a, b, c, d) values();
insert into f(a, b, c, d) values(1, 2, 3, 4);
insert into g values(1, 2, '');
insert into g values('1', '2', '');
insert into g values(1, 2, '');
insert into g values(1, 2, 'insert into g');
insert into g(c) values(1);
insert into g(c) values('hello');
insert into g(b, a) values(1, 2);
insert into g(c, b) values(1, '2');
insert into g(c, b) values('2', 1);
insert into g(c, a) values('2', 1);
insert into g(c, b, a) values(1, 2, '3');
desc f;
desc full f;
desc g;
desc full g;
show table f;
show table full f;
show table g;
show table full g;

